#+TITLE: Dlox: A simple interpreter

* Features
** TODO nor and nand operator
Most of the mainstream programming languages only have 'and', 'or' and 'not' operators. I'm going to try and add 'nor' and 'nand' operator into my language as I felt its need today while writing the interpreter. I think it might come handy at times. 

** TODO Remove semicolons
Its a little annoying to use semicolons in Dlox because for the most part the syntax resembles Python and it does not have semi colons. I get that the author has designed the syntax based on Dart as he works on it for a living. However, in Dlox the use of semicolons is unappealing. So I'm planning to remove it once I add all the features in the language. 
* Questions
1. How does the visitor pattern work?

   I'm not sure how to explain it clearly but I think I have a basic understanding of the concept.

   Essentially, visitor pattern makes it easy to add more operations to existing classes. In Dlox, there are four core classes: Binary, Grouping, Literal and Unary. As I continue to work on the Dlox, I would be adding a number of methods to manipulate the data inside eash of the classes. Generally, without the use of visitor pattern, I would have to add these methods inside every class. But this would make similar methods spread all over the code base. For example, the interpret method for Binary expressions would be nested inside Binary class and the interpret method for Unary expression would be inside Unary class. 

   With the use of Visitor pattern, I could implement similar operations for any number of classes in one file and with the help of polymorphism, make the object access the right method. For interpretring the parsed source code, I have implemented all the operations inside Interpreter.cpp. ~Interpreter::interpret~ is passed a pointer pointing to the Abstract Syntax Tree(AST) and this tree is composed of expressions of types Binary, Literal, Grouping and Unary. For evaluating the tree, ~evaluate()~ calls ~accept()~ method on the passed expression pointer with a pointer to interpreter object itself as argument. Now polymorphism comes into action and helps the interpreter access the right method based on the type of the expression pointer. If the expression pointer points to to a Binary object, it would access ~Interpreter::visitBinaryExpr()~ and if pointer points to some other object, it would call the method specific for that object. This shows how we can group all the methods for interpreting various types of expressions into one file. If not for visitor pattern, I would have implemented the interpret method for every type inside its own class. 

   To make the visitor pattern work, I'm adding a level of indirection: the evaluate method in a Interpreter object, passes itself to a type class (Binary, Unary, Literal, Grouping) and in return the type class calls its specific method (visit[Binary, Literal, Grouping, Unary]Expr()) inside the interpreter object passing a pointer to itself as argument. Now the execution comes back to the interpreter object and the expression is recursively evaluated. To summarize, it follows the path Interpreter -> Expression Type -> Interpreter. The first step (Interpreter -> Expression Type) decides which method gets called (polymorphism) inside the Interpreter object. So this layer of indirection allows us to easily add operations to existing types without modifying the type classes. 

   Usually, its hard to add new operations on existing types without touching the types in OOP style whereas in Functional programming it is easier to add new operations. So essentially the visitor pattern enables us to approximate functional style within OOP. 

2. Difference between Dynamic and Lexical scope? 
   #+begin_src python
     a = 10
     def add(b):
         return a + b
     
     def temp():
         a = 50
         return add(10)
     
     print(temp())
   #+end_src

   *Lexical scope:*
   #+RESULTS:
   : 20
   In lexical scope, the scope of the variable can be determined by its location in the source code without executing it. For example, in the python code above, the value of ~a~ is 50 inside ~temp()~ and in other places its value is 10. Thus we can determine the value of ~a~ inside ~temp()~ by examining the source code. 

   Lexical scope was first introduced in ALGOL. Almost all recent programming language offer lexical scoping as default. 

   *Dynamic scope:*
   #+RESULTS:
   : 60
   In dynamic scope, a reference to the variable points to the most recently initialized value. If the above mentioned code had dynamic scope, the value of ~a~ inside ~add()~ when it is called from ~temp()~ would be 50. Thus the most recently initialized value of 50 is referenced instead of 10. 

   Computer scientists back in the day falsely believed that dynamic scope was faster to execute but this claim has been disproved by Scheme hackers. Emacs Lisp used to have dynamic scope by default until version 27. Also, bash and the original version of Lisp are examples of dynamically scoped programming languages. 
   
* Quick Look
1. *Expression statements:*
   By book's definition, expression statements are expressions with side effects. An other book (K&R) explains expression statements to be expression followed by semicolons and that expression statements do all the real work in C. For example, method calls followed by ~;~ is an expression statement.   

   Since the exact difference between expression and statement is unclear, I'm going to diffrentiate expression and statement. 

   | Expression                      | Statement                        |
   |---------------------------------+----------------------------------|
   | Expression evaluates to a value | Changes the state of the program |
   | Does not have side effects      | Has atleast one side effect      |
   | Eg. ~1 + 2~, ~2~, ~(1 + 4 / 2)~ | Eg. ~print "Hello, world!"~      |

   The points mentioned above are highly generalized and can differ from language to language. 

2. *Imperative programming:*
   Programs that use a sequence of statements to produce the desired output. Statements usually have side effects and it comes in two forms:
   A. Produce output -> print statements
   B. Change the state of the program.
